version: "3.9"
services:
  go-api:
    build: ./go-api
    image: docker-go-wow
    ports:
      - "8080:8080"
    networks: 
      - api
  frontend:
    build: ./frontend
    image: frontend
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    stdin_open: true
    ports:
      - "3000:3000"
    command: yarn start
    networks: 
      - frontend
      - api
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword 
    ports:
      - "5432:5432"
    volumes: 
      - ./data:/var/lib/postgresql/data
    networks:
      - db
      - api
networks: 
  frontend:
  api:
  db: