version: "3.9"
services:
  waker-api:
    build: ./waker-api
    image: waker-api
    volumes:
      - ./waker-api/src:/waker-api/src
      - ./config/:/.ssh/
    ports:
      - "8888:8888"
    networks: 
      - api
    environment:
      SSH_USER: pierre 
      SSH_PRIVATE_KEY_PATH: /.ssh/private_key
      SSH_HOST: 192.168.1.254
  frontend:
    build: ./frontend
    image: frontend
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    stdin_open: true
    ports:
      - "3000:3000"
    command: yarn start
    networks: 
      - frontend
      - api
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword 
    volumes: 
      - ./data:/var/lib/postgresql/data
networks: 
  frontend:
  api: